config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :games do
    resources :rents, only: [:new, :create]
  end
   resources :rents, only: [:show, :edit, :update, :destroy]
end

app/views/shared_games/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/waitoair/rent_a_game" target="_blank"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>This marketplace is made with <i class="fas fa-heart"></i> by Equipe Rocket 🚀 at Le Wagon</p>
  </div>
</div>

app/views/shared_games/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content">
    <div class="container">

    <%= link_to  "Only Old Games", root_path, class:"return-to-home" %>
    
    <div>
      <% if current_user %>
      <%= "Hello, #{current_user.name}!" %>
      <%= link_to "Edit User", edit_user_registration_path, class:"btn" %>
      <%= link_to "Add your Game", new_game_path, class:"btn" %>
      <%# <%= link_to "Edit your Game", edit_game_path, class:"btn" %>
      <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class:"btn"
    %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class:"btn" %>
      <%= link_to "Sign Up", new_user_registration_path, class:"btn" %>
      <% end %>
    </div>
  </div>
</div>