config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :games do
    resources :rents, only: [:new, :create]
  end
   resources :rents, only: [:show, :edit, :update, :destroy]
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :return_date, presence: true
  #validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  #validates :total_days, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def show
    @rent = Rent.find(params[:id])
  end

  def new
    @game = Game.find(params[:game_id])
    @rent = Rent.new
  end

  def create
    @rent = Rent.new(rent_params)
    @rent.game = Game.find(params[:game_id])
    @rent.user = current_user
    @rent.total_days = (@rent.return_date - Date.today).to_i
    @rent.total_price = @rent.total_days * @rent.game.price
    @rent.game.update(available: false)
    @rent.save
    redirect_to @rent
  end

  def update
    @rent = Rent.find(params[:id])
    @rent.total_days = (@rent.return_date - Date.today).to_i
    @rent.total_price = @rent.total_days * @rent.game.price
    @rent.update(rent_params)
    redirect_to @rent
  end

  def edit
    @rent = Rent.find(params[:id])
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.game.update(available: true)
    @rent.destroy
    redirect_to game_path
  end

  private

  def rent_params
    params.require(:rent).permit(:rent_world, :rent_game, :return_date)
  end
end

app/views/rents/edit.html.erb
<div class="container text-form">
  <h1 style="font-family: 'Bebas Neue', cursive;">Rent View</h1>
  <%= form_with(model:[@game, @rent]) do |f| %>
    <%= f.check_box :rent_world%>
    <%= f.label :rent_world%>
    <%= f.check_box :rent_game %>
    <%= f.label :rent_game %>
    <%= f.date_field :return_date, min:Date.today, max:Date.today + 5, class:"check-rent" %>
    <%= f.submit "Submit", class:"btn" %>
  <% end %>
</div>

app/views/rents/new.html.erb
<div class="container rent-form">
  <h1>Rent a game</h1>
  <%= form_with(model:[@game, @rent]) do |f| %>
    <%= f.check_box :rent_world%>
    <%= f.label :rent_world %>
    <%= f.check_box :rent_game %>
    <%= f.label :rent_game %>
    <%= f.date_field :return_date, min:Date.today, max:Date.today + 5, strftime: "%d/%m/%Y", class:"check-rent" %>
    <%= f.submit "Submit", class:"btn" %>
  <%end %>
</div>

app/views/rents/show.html.erb
<div class="container rent-form">
  <h1> Rent: <%= @rent.game.name %> </h1>
  <p> With world: <%= @rent.rent_world ? 'Yes' : 'No' %> </p>
  <p> With game: <%= @rent.rent_game ? 'Yes' : 'No' %> </p>
  <p>Return date: <%= @rent.return_date.strftime("%d %b %Y") %> </p>
  <p>Total price: $ <%= @rent.total_price %> - ( <%= pluralize(@rent.total_days, 'day') %> ) </p>
  <%= link_to  "Back to Homepage", root_path, class:"btn" %>
  <%= link_to  "Edit", edit_rent_path(@rent), class:"btn" %>
</div>