config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :games do
    resources :rents, only: [:new, :create]
  end
   resources :rents, only: [:show, :edit, :update, :destroy]
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy

  has_one_attached :photo
  has_one_attached :video
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 5 }
  validates :category, presence: true
  validates :video, presence: true
  validates :photo, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @game.update(available: true) if @game.rents.where('return_date > ?', Date.today).empty?
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.save
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
    redirect_to @game unless current_user == @game.user
  end

  def update
    @game = Game.find(params[:id])
    redirect_to @game unless current_user == @game.user
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to root_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :description, :category, :price, :photo, :video)
  end
end

app/views/games/edit.html.erb
<h1>Edit Games</h1>
<%= simple_form_for @game do |f| %>
<%= f.input :description %>
<%= f.input :price, input_html: { min: '5.0' } %>
<%= f.submit %>
<% end %>
 <%= link_to "Remove",
                  game_path(@game),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>

app/views/games/index.html.erb
<%# <div class="banner"> %>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" style="height:300px; object-fit:cover;" src="https://images.unsplash.com/photo-1527896573815-b7dd74893deb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=751&q=80" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" style="height:300px; object-fit:cover;" src="https://images.unsplash.com/photo-1555864326-5cf22ef123cf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=747&q=80" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" style="height:300px; object-fit:cover;" src="https://images.unsplash.com/photo-1591462391994-cb7614f54aff?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <div class="games d-flex flex-wrap">
    <% @games.each do |game| %>
      <a href="<%=game_path(game)%>">
        <div class="photo-game" style="background-image: url('<%= cl_image_path game.photo.key, height: 300, crop: :fill if game.photo.attached? %>')">
      </div>
      </a>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <h1 style="font-family:'Bebas Neue', cursive;">New Game</h1>
  <%= simple_form_for @game do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :category %>
  <%= f.input :price, input_html: { min: '5.0' } %>
  <p> Does this game have a world? If yes, check:  <%= f.check_box :world %> </p>
  <%= f.input :photo, as: :file %>
  <%= f.input :video, as: :file %>
  <%= f.submit class:"btn" %>
  <% end %>
  <%= link_to  "Back to Homepage", root_path, class:"btn" %>
</div>

app/views/games/show.html.erb
<video width="1100px" height="350px" loop autoplay muted>
    <source type="video/mp4" src="<%= cl_video_path @game.video.key%>">
 </video>

<div class="container">
  <div class="show_games">
    <h1><%= @game.name %></h1>
    <h2><%= @game.category %></h2>
    <p><%= @game.description %></p>
    <p style="font-weight: bold; font-size:15px;"> $ <%= @game.price %></p>
    <% if @game.available == true %>
      <p style="color:green; font-size:20px; font-weight: bold;">Available</p>
    <% else %> 
     <p style="color:red; font-size:15px; font-weight: bold;"> Unavailable until <%= "#{@game.rents.order(:return_date).last.return_date.strftime("%d %b %Y")}" %> </p>
    <% end %> 
    </div>
</div>

<div class="show_button">
  <%= link_to  "Back to Homepage", root_path, class:"btn" %>
  <% if current_user == @game.user %>
    <%= link_to "Edit Game", edit_game_path(@game), class:"btn" %>
  <% end %>
  <%= link_to "Rent a Game", new_game_rent_path(@game), class:"btn" if @game.available %>
</div>